# Generated by Django 3.2.23 on 2024-01-11 15:22

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.PositiveSmallIntegerField()),
                ('frame_size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstructionsFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('personId', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateOfBirth', models.DateField(verbose_name='Date of birth')),
                ('forename', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('accent', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recordings.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('fmt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.format')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaitem', models.TextField()),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recording', to='recordings.script')),
            ],
        ),
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompts_url', models.CharField(max_length=64)),
                ('instructions_font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.instructionsfont')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('recording_mixer_name', models.CharField(max_length=64)),
                ('playback_mixer_name', models.CharField(max_length=64)),
                ('prompt_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.promptconfig')),
                ('recording_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.recordingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='recordings.speaker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('session', '&&')], name='exclude_overlapping_sessions'),
        ),
    ]
