# Generated by Django 3.2.23 on 2024-01-15 18:37

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.PositiveSmallIntegerField()),
                ('frame_size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaybackMixerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('providerId', models.CharField(max_length=128)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaitem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FilePathField(default='RECS/', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingMixerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('providerId', models.CharField(max_length=128)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('personId', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateOfBirth', models.DateField(verbose_name='Date of birth')),
                ('forename', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('accent', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recordings.speaker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recordingmixername',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='recordingmixername_unique_default'),
        ),
        migrations.AddField(
            model_name='recordingconfig',
            name='fmt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.format', verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='recording',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recording', to='recordings.script'),
        ),
        migrations.AddField(
            model_name='project',
            name='playbackMixerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recordings.playbackmixername'),
        ),
        migrations.AddField(
            model_name='project',
            name='recordingMixerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recordings.recordingmixername'),
        ),
        migrations.AddField(
            model_name='project',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.script'),
        ),
        migrations.AddField(
            model_name='project',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='recordings.speaker'),
        ),
        migrations.AddConstraint(
            model_name='playbackmixername',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='playbackmixername_unique_default'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('session', '&&')], name='exclude_overlapping_sessions'),
        ),
    ]
