# Generated by Django 3.2.23 on 2024-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
