# Generated by Django 3.2.23 on 2024-01-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='prompt_config',
        ),
        migrations.RemoveField(
            model_name='project',
            name='recording_config',
        ),
    ]
