# Generated by Django 3.2.23 on 2024-01-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_alter_recording_mediaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recordings.script'),
        ),
    ]
