# Generated by Django 3.2.23 on 2024-01-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_alter_project_script'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='format',
            name='frame_size',
        ),
        migrations.AddField(
            model_name='format',
            name='bigEndian',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='format',
            name='frameSize',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='format',
            name='sampleRate',
            field=models.PositiveIntegerField(default=48000),
        ),
        migrations.AddField(
            model_name='format',
            name='sampleSizeInBits',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='format',
            name='channels',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
