# Generated by Django 3.2.23 on 2024-01-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_auto_20240117_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='dateOfBirth',
            field=models.DateField(default=None, verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
