# Generated by Django 3.2.23 on 2024-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0008_alter_speaker_forename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='forename',
        ),
    ]
