# Generated by Django 3.2.23 on 2024-01-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0009_remove_speaker_forename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('session__startswith',)},
        ),
    ]
