# Generated by Django 3.2.23 on 2024-01-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0010_alter_project_options'),
        ('recordings', '0010_recording_finalsilence'),
    ]

    operations = [
    ]
