# Generated by Django 3.2.23 on 2024-01-22 16:19

from django.db import migrations, models
import recordings.models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0013_alter_recprompt_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='recprompt',
            name='recording',
            field=models.FileField(null=True, upload_to=recordings.models.upload_path),
        ),
        migrations.AlterField(
            model_name='recprompt',
            name='finalsilence',
            field=models.PositiveIntegerField(default=4000, help_text='Duration in milliseconds'),
        ),
    ]
