# Generated by Django 3.2.23 on 2024-01-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0014_auto_20240122_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='recordings.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='recordings.script'),
        ),
    ]
