# Generated by Django 3.2.23 on 2024-01-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0018_auto_20240122_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='script',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prj', to='recordings.script'),
        ),
        migrations.AlterField(
            model_name='project',
            name='speaker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='recordings.speaker'),
        ),
    ]
