# Generated by Django 3.2.23 on 2024-01-22 22:33

from django.db import migrations


def set_script_attribute_on_project(apps, schema_editor):
    Project = apps.get_model("recordings", "Project")

    for project in Project.objects.filter(scripts__isnull=False):
        if not project.script:
            project.script = project.scripts.first()
            project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("recordings", "0019_auto_20240122_2227"),
    ]

    operations = [migrations.RunPython(set_script_attribute_on_project)]
