# Generated by Django 3.2.23 on 2024-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0022_alter_recprompt_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
