# Generated by Django 3.2.23 on 2024-02-12 13:26

import django.core.validators
from django.db import migrations
import recordings.fields
import recordings.models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0023_project_no_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='release_form',
            field=recordings.fields.CustomFileField(blank=True, null=True, upload_to=recordings.models.upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='recprompt',
            name='recording',
            field=recordings.fields.CustomFileField(blank=True, null=True, upload_to=recordings.models.upload_path, validators=[django.core.validators.FileExtensionValidator(['wav'])]),
        ),
    ]
