# Generated by Django 3.2.23 on 2024-02-19 15:15

import django.core.validators
from django.db import migrations, models
import recordings.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0026_project_microphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('manual', recordings.fields.CustomFileField(upload_to='documentation/manuals', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
