# Generated by Django 3.2.23 on 2024-02-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0027_soundcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='soundcard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recordings.soundcard'),
            preserve_default=False,
        ),
    ]
