# Generated by Django 3.2.23 on 2024-02-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_archive_archive_file'),
        ('recordings', '0029_project_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='reports.archive'),
        ),
    ]
