# Generated by Django 3.2.23 on 2024-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0031_recprompt_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recprompt',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
