# Generated by Django 3.2.23 on 2024-02-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0032_alter_recprompt_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='microphone',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordingconfig',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soundcard',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='microphone',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='unique_microphone_default'),
        ),
        migrations.AddConstraint(
            model_name='recordingconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='unique_recordingconfig_default'),
        ),
        migrations.AddConstraint(
            model_name='soundcard',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('default',), name='unique_soundcard_default'),
        ),
    ]
