# Generated by Django 3.2.23 on 2024-02-22 21:32

from django.db import migrations, models
import django.db.models.deletion
import recordings.models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0033_auto_20240222_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='RecordingConfiguration',
            field=models.ForeignKey(default=recordings.models.RecordingConfig.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='recordings.recordingconfig'),
        ),
        migrations.AlterField(
            model_name='project',
            name='microphone',
            field=models.ForeignKey(default=recordings.models.Microphone.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='recordings.microphone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='playbackMixerName',
            field=models.ForeignKey(default=recordings.models.PlaybackMixerName.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='recordings.playbackmixername'),
        ),
        migrations.AlterField(
            model_name='project',
            name='recordingMixerName',
            field=models.ForeignKey(default=recordings.models.RecordingMixerName.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='recordings.recordingmixername'),
        ),
        migrations.AlterField(
            model_name='project',
            name='soundcard',
            field=models.ForeignKey(default=recordings.models.Soundcard.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='recordings.soundcard'),
        ),
    ]
