# Generated by Django 3.2.23 on 2024-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0034_auto_20240222_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recprompt',
            name='filesize',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
