# Generated by Django 3.2.23 on 2024-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0035_alter_recprompt_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
