# Generated by Django 3.2.23 on 2024-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0036_project_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
