# Generated by Django 4.2.27 on 2026-01-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0039_recordingmixername_interfacename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingconfig',
            name='mode',
            field=models.CharField(choices=[('m', 'manual'), ('p', 'autoprogress'), ('r', 'autorecording')], default='r', max_length=1),
        ),
        migrations.AddField(
            model_name='recordingconfig',
            name='progressToNextUnrecorded',
            field=models.BooleanField(default=True),
        ),
    ]
