# Generated by Django 4.2.27 on 2026-01-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0040_recordingconfig_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, help_text='Channel index starting from 0')),
                ('Format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.format')),
                ('microphone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recordings.microphone')),
            ],
            options={
                'unique_together': {('Format', 'index')},
            },
        ),
    ]
