# Generated by Django 4.2.27 on 2026-01-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0041_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='channels',
        ),
        migrations.AlterField(
            model_name='channel',
            name='Format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='recordings.format'),
        ),
    ]
