# Generated by Django 4.2.27 on 2026-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0042_remove_format_channels_alter_channel_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='recprompt',
            name='recinstructions',
            field=models.CharField(blank=True, choices=[('0', 'fast'), ('1', 'regular'), ('2', 'high-pitch'), ('3', 'low-pitch'), ('4', 'slow'), ('5', 'happy'), ('6', 'sad'), ('7', 'whisper')], default='', max_length=1),
        ),
    ]
