# Generated by Django 4.2.27 on 2026-01-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0043_recprompt_recinstructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recprompt',
            options={'ordering': ('id',)},
        ),
    ]
