# Generated by Django 4.2.27 on 2026-01-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0044_alter_recprompt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recprompt',
            name='recinstructions',
            field=models.CharField(blank=True, choices=[('0', 'fast'), ('1', 'angry'), ('2', 'high-pitch'), ('3', 'low-pitch'), ('4', 'slow'), ('5', 'happy'), ('6', 'sad'), ('7', 'whisper')], default='', max_length=1),
        ),
    ]
