# Generated by Django 4.2.27 on 2026-01-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0045_alter_recprompt_recinstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingconfig',
            name='postRecDelay',
            field=models.PositiveIntegerField(default=500, help_text='Duration in milliseconds'),
        ),
        migrations.AddField(
            model_name='recordingconfig',
            name='preRecDelay',
            field=models.PositiveIntegerField(default=1000, help_text='Duration in milliseconds'),
        ),
    ]
