# Generated by Django 4.2.7 on 2024-01-06 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.PositiveSmallIntegerField()),
                ('frame_size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstructionsFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('forename', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('accent', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('fmt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speech_recorder.format')),
            ],
        ),
        migrations.CreateModel(
            name='PromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompts_url', models.CharField(max_length=64)),
                ('instructions_font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speech_recorder.instructionsfont')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('recording_mixer_name', models.CharField(max_length=64)),
                ('playback_mixer_name', models.CharField(max_length=64)),
                ('prompt_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speech_recorder.promptconfig')),
                ('recording_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speech_recorder.recordingconfig')),
            ],
        ),
    ]
