# Generated by Django 3.2.23 on 2024-01-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_recorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='dob',
            new_name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='id',
        ),
        migrations.AddField(
            model_name='speaker',
            name='personId',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
