# Generated by Django 3.2.23 on 2024-02-19 17:40

import django.core.validators
from django.db import migrations, models
import recordings.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive",
                    recordings.fields.CustomFileField(
                        upload_to="archived",
                        validators=[
                            django.core.validators.FileExtensionValidator(["zip"])
                        ],
                    ),
                ),
            ],
        ),
    ]
