# Generated by Django 3.2.23 on 2024-02-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('equipment', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='reports.description'),
            preserve_default=False,
        ),
    ]
