# Generated by Django 3.2.23 on 2024-02-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20240219_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='archive',
            new_name='file',
        ),
    ]
