# Generated by Django 3.2.23 on 2024-09-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_archive_archive_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ('-file',)},
        ),
    ]
