# Generated by Django 5.0.1 on 2024-01-06 15:51

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speech_recorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech_recorder.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('session', '&&')], name='exclude_overlapping_sessions'),
        ),
    ]
