# Generated by Django 3.2.23 on 2024-01-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech_recorder', '0003_speaker_email'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='project',
        ),
        migrations.AddField(
            model_name='booking',
            name='speaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='speech_recorder.speaker'),
            preserve_default=False,
        ),
    ]
